version: '3.9'

services:
  db:
    image: postgres:15
    container_name: insightly-db
    environment:
      POSTGRES_DB: insightly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend-Insightly
      dockerfile: Dockerfile
    container_name: insightly-backend
    restart: always
    env_file:
      - ./backend-Insightly/.env
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npx prisma generate && npx prisma migrate deploy && node dist/main"
    volumes:
      - ./backend-Insightly/prisma:/app/prisma

  frontend:
    build:
      context: ./insightly-frontend
      dockerfile: Dockerfile
    container_name: insightly-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://insightly-alb-570198500.eu-west-2.elb.amazonaws.com/api
    depends_on:
      - backend

volumes:
  db-data:
